/* The one sign-in everybody in the team uses.

   ── HOW TO CHANGE THE PASSWORD ────────────────────────────────────────
   Open tools/set-password.html in a browser, type the new user name and
   password, and it prints the three lines below ready to paste. Then
   commit this file. There is nothing else to change and nobody has to
   clear their browser — every machine reads this file on load.

   ── WHAT THIS IS AND IS NOT ───────────────────────────────────────────
   This repository is public and the site is static, so treat this file as
   public knowledge: the password is not stored here, but the PBKDF2 hash
   of it is, and a short or guessable password can be worked back out of a
   hash offline by anyone who wants to. Someone can also simply type a
   page's URL and skip the sign-in entirely, because there is no server to
   stop them.

   So: pick a password used for NOTHING ELSE at the company, and read the
   sign-in as the lock on an office door — it keeps out whoever wanders
   past the browser, not whoever is after the numbers. */
window.AUTH_CONFIG = {
  // Shown on the sign-in form as the name to type.
  user: 'synaccweb',

  // PBKDF2-SHA256 of the password, 150,000 iterations, with the salt below.
  // Generated by tools/set-password.html — do not hand-edit.
  salt: '2d3ae1c95a634b25974900ff44703078',
  hash: '3bc66360c4ea8f9252be81575c915728ba283796faee84e691feecd5b7ef0e8b',
  iter: 150000,
};
